name: Sanity Check Pipe

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Full pipeline
      run: python full_pipe.py
