name: Sanity Check Pipe

on:
  push:
    branches: [main, 7-refactor-and-cicd]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t vessel_image .

    - name: Run program inside Docker container
      run: docker run vessel_image
